### ISSUE TITLE
LoadError: cannot load such file -- sqrl/check/server

### ISSUE THREAD

**Issue by dbadia** [JustinLove/sqrl_check#1]
Any clues on this error? 
I installed rake, just cloned the repo, cd into it, and run the command.

```
dave@jj:/opt/sqrl_check$ rake test["http://localhost:8081/sqrlexample/login",true] --trace
rake aborted!
LoadError: cannot load such file -- sqrl/check/server
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/sqrl_check/Rakefile:1:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:687:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:94:in `block in load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:93:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:77:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
/usr/bin/rake:27:in `<main>'
```

Thanks!
Dave

**Comment by JustinLove** [comment]
What are your ruby and gem versions?

I think RVM might be incorporating a process that wraps common ruby executables for bundler, so you might try `bundle exec rake .....`

Here are mine:

```
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
bundler (1.13.6)
bundler-unload (1.0.2)
did_you_mean (1.0.0)
executable-hooks (1.3.2)
ffi (1.9.14)
ffi-compiler (1.0.1)
gem-wrappers (1.2.7)
httpclient (2.8.2.4)
io-console (0.4.5)
json (1.8.3)
minitest (5.9.1, 5.8.3)
minitest-hooks (1.4.0)
net-telnet (0.1.1)
power_assert (0.2.6)
psych (2.0.17)
rake (11.3.0, 10.4.2)
rbnacl (3.4.0)
rdoc (4.2.1)
redcarpet (3.3.4)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
scrypt (3.0.3)
test-unit (3.1.5)
```

**Comment by dbadia** [comment]
Running with bundle install gave me a better error message, apparently I never ran bundle install

```
dave@jj:/opt/sqrl_check$ bundle exec rake test["http://localhost:8081/sqrlexample/login",true]
git://github.com/JustinLove/sqrl_auth.git (at master@b980e18) is not yet checked out. Run `bundle install` first.
```

But when I run `bundle install` I get errors

```
dave@jj:/opt/sqrl_check$ bundle install
Fetching git://github.com/JustinLove/sqrl_auth.git
fatal: Could not parse object 'b980e186a23ef91fb0c6ac1a23c9d511cfb825a9'.
Git error: command `git reset --hard b980e186a23ef91fb0c6ac1a23c9d511cfb825a9` in directory /home/dave/.bundle/ruby/2.1.0/sqrl_auth-b980e186a23e has failed.
If this error persists you could try removing the cache directory '/home/dave/.bundle/cache/git/sqrl_auth-a301af5183c66c0591299638bcec49268c754906'
```

Removed the cache directory as suggested but it didn't help

```
dave@jj:/opt/sqrl_check$ rm -rf /home/dave/.bundle/cache/git/sqrl_auth-a301af5183c66c0591299638bcec49268c754906
dave@jj:/opt/sqrl_check$ bundle install
Fetching git://github.com/JustinLove/sqrl_auth.git
fatal: Could not parse object 'b980e186a23ef91fb0c6ac1a23c9d511cfb825a9'.
Git error: command `git reset --hard b980e186a23ef91fb0c6ac1a23c9d511cfb825a9` in directory /home/dave/.bundle/ruby/2.1.0/sqrl_auth-b980e186a23e has failed.
If this error persists you could try removing the cache directory '/home/dave/.bundle/cache/git/sqrl_auth-a301af5183c66c0591299638bcec49268c754906'
```

Here is the version info:

```
dave@jj:/opt/sqrl_check$ ruby --version
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

dave@jj:/opt/sqrl_check$ gem list

*** LOCAL GEMS ***

addressable (2.4.0)
backports (3.6.8)
bigdecimal (1.2.4)
bundler (1.13.6)
ethon (0.9.1)
faraday (0.10.0)
faraday_middleware (0.10.1)
ffi (1.9.14)
gh (0.15.0)
highline (1.7.8)
io-console (0.4.2)
json (1.8.1)
launchy (2.4.3)
minitest (4.7.5)
multi_json (1.12.1)
multipart-post (2.0.0)
net-http-persistent (2.9.4)
net-http-pipeline (1.0.1)
psych (2.0.5)
pusher-client (0.6.2)
rake (10.3.2, 10.1.0)
rdoc (4.1.0)
test-unit (2.1.5.0)
travis (1.8.4)
typhoeus (0.8.0)
websocket (1.2.3)


```

**Comment by JustinLove** [comment]
Ooops, looks like bundler was syncing to some tweaks in my local repos, and I forgot there was anything that needed updating when I published sqrl-check. If `bundle install` doesn't refresh the dependency repo, than `bundle update` ought to.

**Comment by dbadia** [comment]
Ok, that helped.  Looks like I forgot to run the bundle command before my last test.  I installed bunde, ran `bundle install `and `bundle update` and now I see the tests hitting my server.

All of the tests are failing against my server, from looking at the logs it appears opt=false is being sent in the client param, which I believe is invalid per https://www.grc.com/sqrl/semantics.htm

Here is the raw output from my logs:
`Processing SQRL client request: nut=AgFAZ-jm2ORz5ym0FVxNuw  sfn=c3FybGphdmEudGVjaA  cor=mi91F1oVn-MLceQhi9YN1aYYnkDi37S1KjTFLefptPw  client=dmVyPTENCmNtZD1pZGVudA0Kb3B0PWZhbHNlDQppZGs9TjJEYTl0ZjJ6ODlNVEJGTHNUYVFjd21OSlVlTk55ZHJaVlZhQjhfazk3QQ0Kc3VrPVFiWjA5MFhRWWp0UE5GWmZialVsdnNqWWl0TGhJbzgyYV9Mb3VZRVBjM0kNCnZ1az1CRjVaMDJZdUNZN09lRHNyQ2pQU0dSVFVFaEdZZHc4eHFyeVk5UTVBMkJv  server=c3FybDovL3NxcmxqYXZhLnRlY2g6MjAwMDAvc3FybGV4YW1wbGUvc3FybGJjP251dD1BZ0ZBWi1qbTJPUno1eW0wRlZ4TnV3JnNmbj1jM0Z5YkdwaGRtRXVkR1ZqYUEmY29yPW1pOTFGMW9Wbi1NTGNlUWhpOVlOMWFZWW5rRGkzN1MxS2pURkxlZnB0UHc  ids=ZsyY35nxpjsAS5U1W8EyHw1BgZr4UKiK06WxY8f4Eq1i6cnuFQsOvVDs6KMwvWySUtv_c64epmA0qLVrWnMkDA`

And the decoded client string
```
ver=1
cmd=ident
opt=false
idk=N2Da9tf2z89MTBFLsTaQcwmNJUeNNydrZVVaB8_k97A
suk=QbZ090XQYjtPNFZfbjUlvsjYitLhIo82a_LouYEPc3I
vuk=BF5Z02YuCY7OeDsrCjPSGRTUEhGYdw8xqryY9Q5A2Bo

```

I am running the test like this:

`dave@jj:/opt/sqrl_check$ bundle exec rake test["https://sqrljava.tech:20000/sqrlexample/login",true]`

**Comment by JustinLove** [comment]
Good catch. I wasn't typically printing out client messages, and my servers weren't strict with opt since it seemed like a likely place for extensions.
